### ISSUE TITLE
v2.8.3上传压缩包报错

### ISSUE THREAD

**Issue by Xiaoph123** [jamebal/jmal-cloud-view#102]
我使用以下命令进行更新2.8.3
```yaml
docker exec -it jmalcloud_mongodb mongodump -d jmalcloud -o /dump/v2.8.2 --gzip --quiet
docker-compose pull && docker-compose up -d
./jc.sh restart
```
更新后我上传压缩包提示报错：
<img width="1111" alt="PixPin_2024-05-18_15-02-54" src="https://github.com/jamebal/jmal-cloud-view/assets/106538519/71d0cc76-2169-45a1-8fa4-ab64006eb6de">

一直显示合并中，我右键jmalcloud刷新，上传的压缩包显示出来了并且文件正常，但是传输界面还是一直卡着

**Comment by jamebal** [comment]
感谢反馈，请问如何重现

**Comment by Xiaoph123** [comment]
> 感谢反馈，请问如何重现

正如题中所示，我是从2.8.2运行了上面的3条命令之后，就出现了上传压缩包报错

**Comment by jamebal** [comment]
是所有的压缩包,还是特定的压缩包,每次都会出现吗?

**Comment by Xiaoph123** [comment]
> 是所有的压缩包,还是特定的压缩包,每次都会出现吗?

是的，目前我只测试rar，zip格式的，每次上传都会报这个错，但是你刷新后，压缩包确是上传上去了

**Comment by jamebal** [comment]
麻烦使用`docker logs jmalcloud_server`看看错误日志

**Comment by Xiaoph123** [comment]
> 麻烦使用`docker logs jmalcloud_server`看看错误日志

请稍等

**Comment by Xiaoph123** [comment]
> 麻烦使用`docker logs jmalcloud_server`看看错误日志

其实2.8.2也遇到过这个问题，待会我把详细情况说明一下

**Comment by Xiaoph123** [comment]
> docker logs jmalcloud_server

关于v2.8.2会出现上传压缩包报错的实现：

当时我反馈了wevDAV在windows下无法上传文件，修改文件，重命名等问题后您让我修改docker-compose.yml

docker-compose.yml配置一：

```yaml
version: "3"
services:
  mongo:
    container_name: ${CONTAINER_NAME_PREFIX}_mongodb
    image: mongo:4.4
    environment:
      TZ: Asia/Shanghai
    ports:
      - 27018:27017
    volumes:
      - ${RESOURCE_DB_PATH}/data/db:/data/db
      - ${RESOURCE_DB_PATH}/custom:/etc/mongo
      - ${RESOURCE_DB_PATH}/backup:/dump
    restart: unless-stopped
    command: --wiredTigerCacheSizeGB 0.5
  jmalcloud:
    container_name: ${CONTAINER_NAME_PREFIX}_server
    image: jmal/jmalcloud:latest
    environment:
      MONGODB_URI: mongodb://mongo:27017/jmalcloud
      TZ: Asia/Shanghai
    ports:
      - ${SERVER_PORT}:8088
      - ${FTP_SERVER_PORT}:8089
    volumes:
      - ${RESOURCE_FILE_PATH}:/jmalcloud/files/
    restart: always
  nginx:
    container_name: ${CONTAINER_NAME_PREFIX}_nginx
    image: jmal/jmalcloud-nginx:latest
    ports:
      - ${APP_PORT}:80
      - ${BLOG_PORT}:8089
    environment:
      TZ: Asia/Shanghai
    links:
      - jmalcloud
      - office
      - drawio-webapp
    restart: always
  office:
    container_name: ${CONTAINER_NAME_PREFIX}_office
    image: onlyoffice/documentserver:${OFFICE_IMAGE_VERSION}
    environment:
      TZ: Asia/Shanghai
    restart: always
  drawio-webapp:
    container_name: ${CONTAINER_NAME_PREFIX}_drawio
    image: jgraph/drawio:${DRAWIO_IMAGE_VERSION}
    environment:
      TZ: Asia/Shanghai
    restart: always
networks: {}

```

docker-compose.yml配置二：

```yaml
version: "3"
services:
  jmalcloud:
    container_name: jmalcloud_server
    image: jmal/jmalcloud:latest
    environment:
      MONGODB_URI: mongodb://mongo:27017/jmalcloud
      TZ: Asia/Shanghai
    volumes:
      - ./docker/jmalcloud/files:/jmalcloud/files/
    restart: unless-stopped
  mongo:
    container_name: jmalcloud_mongodb
    image: mongo:4.4
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./docker/jmalcloud/mongodb/data/db:/data/db
    restart: unless-stopped
    command: --wiredTigerCacheSizeGB 0.5
  nginx:
    container_name: jmalcloud_nginx
    image: jmal/jmalcloud-nginx:latest
    ports:
      - 7070:80
      - 7071:8089
    environment:
      TZ: Asia/Shanghai
    links:
      - jmalcloud
      - office
      - drawio-webapp
    restart: unless-stopped
  office: # Optional
    container_name: jmalcloud_office
    image: onlyoffice/documentserver:7.0.0.132
    environment:
      TZ: Asia/Shanghai
    restart: unless-stopped
  drawio-webapp: # Optional
    container_name: jmalcloud_drawio
    image: jgraph/drawio:20.2.3
    environment:
      TZ: Asia/Shanghai
    restart: unless-stopped
```

在v2.8.2版本时我将docker-compose.yml换成了配置二，出现上传压缩包报错，当我换成配置一后上传正常

在v2.8.3版本时无论我将docker-compose.yml换成配置一时会出现合并文件失败，但是待会又出现上传成功，他会把我的压缩包自动解压出来。

![image](https://github.com/jamebal/jmal-cloud-view/assets/106538519/1e9155b1-387b-48a4-8e46-a5e1882699c6)


当我使用配置二就会出现上传压缩包报错
