### ISSUE TITLE
全文搜索不起作用

### ISSUE THREAD

**Issue by death4444** [jamebal/jmal-cloud-view#129]
按照v2.8.0的定义------全文搜索,搜索范围: 文件名、标签名和文件文本内容
实测如下：
![image](https://github.com/jamebal/jmal-cloud-view/assets/26320543/ee587aa4-d601-4c25-bb8f-e4307e6cc2db)
![image](https://github.com/jamebal/jmal-cloud-view/assets/26320543/d590c68d-9b84-417d-97ad-93f7d97134bc)
txt都搜不出来！pdf以及word或者PPT就更搜不出来了。
![image](https://github.com/jamebal/jmal-cloud-view/assets/26320543/bd94b8f4-97a2-4fa1-af38-855f127dd6d1)
 jmalcloud_server 以及 jmalcloud_mongodb 日志均没有异常

**Comment by death4444** [comment]
> 在根目录搜索呢

这种基操肯定试过了撒，还是不得行！blog里面的内容可以在blog的搜索下面，全文搜索到。cloud这边不行！

**Comment by jamebal** [comment]
在jmalcloud_server下添加一个环境变量:`LOG_LEVEL: info`, 重启后搜索看看日志
```yaml
  jmalcloud:
    container_name: jmalcloud_server
    image: jmal/jmalcloud:latest
    environment:
      LOG_LEVEL: info
```
