### ISSUE TITLE
关于jmalcloud云盘数据迁移问题总结

### ISSUE THREAD

**Issue by Xiaoph123** [jamebal/jmal-cloud-view#168]
如果你有想更换带宽更大的服务器用来提高jmalcloud云盘的上传下载速度，但同时不想丢失原来的文件数据、账户信息等，那么你可以参考我的做法，将原服务器上的数据迁移到新的服务器上。

## 环境：

>原服务器：Centos 7.9
>
>新服务器：Centos 7.9
>
>数据存放位置：/opt/sdb1mount/jmal-cloud-server/docker/jmalcloud/（以我自己的云盘存放位置举例）

### **备份mongodb数据库**

``` shell
docker exec -it jmalcloud_mongodb mongodump -d jmalcloud -o /dump/jamlcloudbak --gzip --quiet
```

执行该命令后, 会在/opt/sdb1mount/jmal-cloud-server/docker/jmalcloud/mongodb/backup/jamlcloudbak目录下会生成名为jmalcloud的文件夹, 里面就是数据库文件

### 复制网盘文件和数据库文件到新服务器

网盘中所有文件均在该目录下`/opt/sdb1mount/jmal-cloud-server/docker/jmalcloud/files`

所有网盘文件和数据库文件以及`docker-compose.yml`全部在该目录中`/opt/sdb1mount/jmal-cloud-server`, 压缩该目录复制到新服务器再解压即可

### 压缩源文件

如linux系统可以使用zip进行压缩

如果你没有zip工具需要使用yum安装

```shell
yum install zip -y
cd /opt/sdb1mount/
zip -r jmal-cloud-server.zip jmal-cloud-server
```

### 上传新的服务器

使用scp命令把`jmal-cloud-server.zip`传输到新服务上并解压（如果你的数据文件比较多，这将是一个漫长的过程）

```shell
scp jmal-cloud-server.zip root@公网ip:/opt/sdb1mount/

#在新服务器中解压
cd /opt/sdb1mount/
unzip jmal-cloud-server.zip
```

### 在新服务器中恢复mongodb数据库

```shell
cd /opt/sdb1mount/jmal-cloud-server
# 启动镜像
docker-compose up -d

# 启动完之后恢复数据库
docker exec -it jmalcloud_mongodb mongorestore -d jmalcloud --dir /dump/jamlcloudbak --gzip --quiet
docker restart jmalcloud_office
```

如果`docker-compose up -d`命令因为网络问题一直拉取不到镜像，那就手动备份原服务器中的镜像文件

### 导出镜像

在原服务器中，使用 `docker save` 命令将镜像导出为一个 `tar` 文件。

> 命令语法：docker save -o my_image.tar <image_name>:<tag>

```shell
docker save -o my_image1.tar jmal/jmalcloud:latest
docker save -o my_image2.tar jmal/jmalcloud-nginx:latest
docker save -o my_image3.tar mongo:4.4
docker save -o my_image4.tar jgraph/drawio:20.2.3
docker save -o my_image5.tar onlyoffice/documentserver:7.0.0.132
```

### 传输镜像文件

将导出的 tar 文件 (例如：my_image1.tar) 通过 USB、局域网、移动硬盘或者scp命令等方式传输到目标机器上。

### 导入镜像

在新服务器上，使用`docker load`命令导入镜像。

```shell
docker load -i my_image1.tar
docker load -i my_image2.tar
docker load -i my_image3.tar
docker load -i my_image4.tar
docker load -i my_image5.tar
```

这样，目标机器上就可以使用该镜像了，可以使用 docker images 命令来验证镜像是否成功导入。

```shell
docker images
```

这将显示所有可用的 Docker 镜像，包括你刚刚导入的镜像。

### 问题一：

如果你登录网盘之后发现你的文件可以显示但是无法访问或者访问进去后是空文件，那么可能是你的`docker-compose.yml`文件内镜像的路径有问题，你需要将`docker-compose.yml`文件中的${RESOURCE FILE PATH}字段替换为你实际的路径

以下是我的`docker-compose.yml`文件配置：

```yaml
version: "3"
services:
  mongo:
    container_name: ${CONTAINER_NAME_PREFIX}_mongodb
    image: mongo:4.4
    environment:
      TZ: Asia/Shanghai
    ports:
      - 27018:27017
    volumes:
      - /opt/sdb1mount/jmal-cloud-server/docker/jmalcloud/mongodb/data/db:/data/db
      - /opt/sdb1mount/jmal-cloud-server/docker/jmalcloud/mongodb/custom:/etc/mongo
      - /opt/sdb1mount/jmal-cloud-server/docker/jmalcloud/mongodb/backup:/dump
    restart: unless-stopped
    command: --wiredTigerCacheSizeGB 0.5
  jmalcloud:
    container_name: ${CONTAINER_NAME_PREFIX}_server
    image: jmal/jmalcloud:latest
    environment:
      MONGODB_URI: mongodb://mongo:27017/jmalcloud
      TZ: Asia/Shanghai
    ports:
      - ${SERVER_PORT}:8088
      - ${FTP_SERVER_PORT}:8089
    volumes:
      - /opt/sdb1mount/jmal-cloud-server/docker/jmalcloud/files:/jmalcloud/files/
    restart: always
  nginx:
    container_name: ${CONTAINER_NAME_PREFIX}_nginx
    image: jmal/jmalcloud-nginx:latest
    ports:
      - ${APP_PORT}:80
      - ${BLOG_PORT}:8089
    environment:
      TZ: Asia/Shanghai
    links:
      - jmalcloud
      - office
      - drawio-webapp
    restart: always
  office:
    container_name: ${CONTAINER_NAME_PREFIX}_office
    image: onlyoffice/documentserver:${OFFICE_IMAGE_VERSION}
    dns:
        - 223.5.5.5
    environment:
      TZ: Asia/Shanghai
    restart: always
  drawio-webapp:
    container_name: ${CONTAINER_NAME_PREFIX}_drawio
    image: jgraph/drawio:${DRAWIO_IMAGE_VERSION}
    environment:
      TZ: Asia/Shanghai
    restart: always
networks: {}
```

### 问题二

如果你的office文件预览不了，那么可能是你的dns有问题，你需要修改`/etc/hosts`文件，填入你的公网IP+域名

```shell
vi /etc/hosts
```

![image](https://github.com/jamebal/jmal-cloud-view/assets/106538519/ae2a0494-8e2d-44b9-b928-10d3dd686999)

修改完之后，wq保存退出，并重启云盘

```shell
cd /opt/sdb1mount/jmal-cloud-server
./jc.sh restart
```

等待加载完成，officeoline需要加载一段时间，加载完成后访问你的云盘，现在你应该能正常预览office文件。
