### ISSUE TITLE
docker-compose使用user: "1000:100"参数报错。

### ISSUE THREAD

**Issue by kokojacket** [jamebal/jmal-cloud-view#196]
为了让jma中建立的文件和文件夹能在主机上管理。
尝试了用user: "1000:100"参数，发现无法启动。
建议优化一下。
https://padeoe.com/docker-volume-file-permission-problem/

**Comment by jamebal** [comment]
v2.9.2加入 `PUID`和`PGID`
```yaml
    environment:
      PUID: 1000
      PGID: 1000
```
