### ISSUE TITLE
数据恢复问题

### ISSUE THREAD

**Issue by Xiaoph123** [jamebal/jmal-cloud-view#220]
我因为服务器被黑导致数据库清空，我回滚到没被攻击前
把jmalcloud的mongo数据库备份了一下 : docker exec -it jmalcloud_mongodb mongodump -d jmalcloud -o /dump/jamlcloudbak --gzip --quiet

然后我把其中一个用户的文件，也备份了下：/root/jmal-cloud-server/docker/jmalcloud/files   只是其中一个非管理员用户
然后我重装系统，重新安装jmalcloud，
使用下面两条命令恢复数据库，并且把非管理员用户的文件放进了/root/jmal-cloud-server/docker/jmalcloud/files  文件下
# 启动镜像
docker-compose up -d

# 启动完之后恢复数据库
docker exec -it jmalcloud_mongodb mongorestore -d jmalcloud --dir /dump/jamlcloudbak --gzip --quiet

于是我登录查看却发现登录不上，我不知道我这么操作是否能行。

**Comment by jamebal** [comment]
回滚到没被攻击前且还没备份到时候可以正常登录吗?

**Comment by Xiaoph123** [comment]
> 回滚到没被攻击前且还没备份到时候可以正常登录吗?

可以的

**Comment by Xiaoph123** [comment]
> 回滚到没被攻击前且还没备份到时候可以正常登录吗?

我只是测试了一下，

**Comment by Xiaoph123** [comment]
> > 回滚到没被攻击前且还没备份到时候可以正常登录吗?
> 
> 可以的

/root/jmal-cloud-server/docker/jmalcloud/files下我只上传了一个非管理员用户的数据，并没有上传全部的

**Comment by Xiaoph123** [comment]
> > > 回滚到没被攻击前且还没备份到时候可以正常登录吗?
> > 
> > 可以的
> 
> /root/jmal-cloud-server/docker/jmalcloud/files下我只上传了一个非管理员用户的数据，并没有上传全部的

**Comment by jamebal** [comment]
重装jmalcloud后有设置mongodb的密码吗

**Comment by Xiaoph123** [comment]
> 重装jmalcloud后有设置mongodb的密码吗

没有设密码，我忘记了，我之前配置了，我现在配置上试试

**Comment by jamebal** [comment]
> > 重装jmalcloud后有设置mongodb的密码吗
> 
> 没有设密码，我忘记了，我之前配置了，我现在配置上试试
这个不影响, 就是执行备份命令的时候有没有设置密码: docker exec -it jmalcloud_mongodb mongodump -d jmalcloud -o /dump/jamlcloudbak --gzip --quiet

**Comment by jamebal** [comment]
看这个文件里面有没有东西: /dump/jamlcloudbak

**Comment by Xiaoph123** [comment]
> 看这个文件里面有没有东西: /dump/jamlcloudbak

/dump/jamlcloudbak。具体在什么位置，我没找到

**Comment by Xiaoph123** [comment]
> > > 重装jmalcloud后有设置mongodb的密码吗
> > 
> > 没有设密码，我忘记了，我之前配置了，我现在配置上试试
> 这个不影响, 就是执行备份命令的时候有没有设置密码: docker exec -it jmalcloud_mongodb mongodump -d jmalcloud -o /dump/jamlcloudbak --gzip --quiet
> 
执行备份的时候没有备份，在备份前我是设置了密码

**Comment by jamebal** [comment]
docker-compose.yml文件中:  对应的/dump目录
```yml
  mongo:
    container_name: jmalcloud_mongodb
    image: mongo:4.4
    environment:
      TZ: "Asia/Shanghai"
    volumes:
      - ./docker/jmalcloud/mongodb/data/db:/data/db
      - ./docker/jmalcloud/mongodb/backup:/dump
```
