### ISSUE TITLE
请教下如何添加常用ttf ttc字体

### ISSUE THREAD

**Issue by gzxiexl** [jamebal/jmal-cloud-view#232]
感谢大佬做出这么好的软件，请教下如何添加常用ttf ttc字体

**Comment by jamebal** [comment]
在onlyoffice中添加字体吗?

**Comment by gzxiexl** [comment]
> 在onlyoffice中添加字体吗? 

是的

**Comment by jamebal** [comment]
为了确保在重建 Docker 容器后字体仍然存在，你可以将字体文件存放在宿主机上，并将该目录挂载到容器中。这可以通过 Docker 的挂载卷功能来实现。以下是具体步骤：

**1.	在宿主机上创建一个目录来存放字体文件：**
例如，你可以在 /opt/fonts 目录中存放字体文件。
```shell
mkdir -p /opt/fonts
cp /path/to/your/fonts/*.ttf /opt/fonts/
cp /path/to/your/fonts/*.ttc /opt/fonts/
```

**2.	修改 Docker Compose 文件或 Docker 启动命令：**
如果你是通过 Docker Compose 来管理 OnlyOffice 容器，编辑 docker-compose.yml 文件。如果是通过 docker run 命令启动容器，可以直接在命令中添加挂载卷。
**Docker Compose 示例：**
```yaml
services:
  onlyoffice:
    image: onlyoffice/documentserver
    volumes:
      - /opt/fonts:/usr/share/fonts/truetype/custom
```
**4.	执行`docker-compose up -d`使其生效：**
```shell
docker-compose up -d
```
