### ISSUE TITLE
希望能有配置可以去除内置的onlyoffice

### ISSUE THREAD

**Issue by fengdu126** [jamebal/jmal-cloud-view#277]
现在云主机上面的jmal经常内存占用或者cpu占用100%，发现停用onlyoffice会有改善。
现在在配置文件里面把后面的onlyoffice启动依赖去掉，但nginx不能启动，希望能有选项可以去除onlyoffice不用启动
![image](https://github.com/user-attachments/assets/b9ccc278-cd35-4f2e-af50-90cdf5e77400)

**Comment by fengdu126** [comment]
最好是能把nginx也去掉，可以用配置外部的ngixn来代替

**Comment by jamebal** [comment]
这个nginx,你可以挂载自己的配置

**Comment by fengdu126** [comment]
> 这个nginx,你可以挂载自己的配置

ngnix应该没啥影响，这个不用管了，主要是怎么能自动停用内置的onlyoffice

**Comment by jamebal** [comment]
去掉docker-compose.yml中的office就行了
```yml
services:
  mongo:
    container_name: jmalcloud_mongodb
    image: mongo:4.4
    environment:
      TZ: "Asia/Shanghai"
    volumes:
      - ./docker/jmalcloud/mongodb/data/db:/data/db
      - ./docker/jmalcloud/mongodb/backup:/dump
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 3
    command: --wiredTigerCacheSizeGB 0.5

  jmalcloud:
    container_name: jmalcloud_server
    image: jmal/jmalcloud:latest
    environment:
      MONGODB_URI: "mongodb://mongo:27017/jmalcloud"
      TZ: "Asia/Shanghai"
      JVM_OPTS: "-Xms256m -Xmx512m"
    volumes:
      - ./docker/jmalcloud/files:/jmalcloud/files/
    restart: unless-stopped
    depends_on:
      mongo:
        condition: service_healthy

  nginx:
    container_name: jmalcloud_nginx
    image: jmal/jmalcloud-nginx:latest
    ports:
      - 7070:80
      - 7071:8089
    environment:
      TZ: "Asia/Shanghai"
    links:
      - jmalcloud
    restart: unless-stopped
```
