### ISSUE TITLE
大量文件重建索引卡住

### ISSUE THREAD

**Issue by sansi98h** [jamebal/jmal-cloud-view#286]
没有使用网盘上传文件，而是**直接将文件移动到用户目录下**，这时候网盘是没有看到刚移动进去的文件，然后点击重建索引，基本上每次涨几个百分比，然后就卡住了，只有不断重启容器，然后重新索引，继续卡住。
![image](https://github.com/user-attachments/assets/e2e0515a-24b2-4f11-90ff-20679e713dd8)
这是重建记录，最后一次是头天晚上9点多，到现在一直卡主不动
![image](https://github.com/user-attachments/assets/a97da69e-40d1-4b40-ac02-0d05ff2daf0a)
期间也查看了下数据库的记录，只有在点击重建索引后，数据库会有大量的操作，但是只持续了几十秒没了，同样重建索引的进度也不再更新。
这是容器日志，只能看见不断重启，其它无任何异常
![image](https://github.com/user-attachments/assets/5a885f53-b891-48fb-9bad-ca736b92d92d)

**Comment by jamebal** [comment]
大概有多少文件,pdf多不多

**Comment by jamebal** [comment]
在jmalcloud_server中加入环境变量: `LOG_LEVEL`: info, 重启后重建索引,再看看日志
```yaml
services:
  jmalcloud:
    container_name: jmalcloud_server
    image: ghcr.io/jamebal/jmalcloud:test
    environment:
      MONGODB_URI: ***
      LOG_LEVEL: info
      JVM_OPTS: -Xms512m -Xmx1024m
```
