### ISSUE TITLE
配置外部onlyoffice时，打开文档一直卡在空白状态

### ISSUE THREAD

**Issue by catbei2020** [jamebal/jmal-cloud-view#287]
如图，配置外部访问onlyoffice，回调地址应该设置成站点的地址吗？但是设置成站点地址，打开文档一直卡在空白状态。
![微信截图_20240922222407](https://github.com/user-attachments/assets/88855189-75b7-4c11-80c6-06dfe1f8c110)
![微信截图_20240922222957](https://github.com/user-attachments/assets/090053a8-2af6-41e8-b404-a4f960965ab8)

**Comment by jamebal** [comment]
回调地址是服务端的实际地址: 以下二选一
1. 网盘地址 + `/api`
2. 在docker-compose.yml中暴露服务端端口:
列如: 这里暴露了7072, 则回调地址为: http://宿主机ip:7072
```yaml
services:
  jmalcloud:
    container_name: jmalcloud_server
    image: jmal/jmalcloud:latest
    ports:
      - 7072:8088
```

**Comment by catbei2020** [comment]
试了一下，移动端可以正常打开，电脑端就一直卡状态，我only用的是自己的8.1的版本，会不会是适配的问题呢？

**Comment by jamebal** [comment]
yaml文件删除office, nginx中的links也要删除office
```yaml
services:
  mongo:
    container_name: jmalcloud_mongodb
    image: mongo:4.4
    environment:
      TZ: "Asia/Shanghai"
    volumes:
      - ./docker/jmalcloud/mongodb/data/db:/data/db
      - ./docker/jmalcloud/mongodb/backup:/dump
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 3
    command: --wiredTigerCacheSizeGB 0.5

  jmalcloud:
    container_name: jmalcloud_server
    image: jmal/jmalcloud:latest
    environment:
      MONGODB_URI: "mongodb://mongo:27017/jmalcloud"
      TZ: "Asia/Shanghai"
      JVM_OPTS: "-Xms256m -Xmx512m"
    volumes:
      - ./docker/jmalcloud/files:/jmalcloud/files/
    restart: unless-stopped
    depends_on:
      mongo:
        condition: service_healthy

  nginx:
    container_name: jmalcloud_nginx
    image: jmal/jmalcloud-nginx:latest
    ports:
      - 7070:80
      - 7071:8089
    environment:
      TZ: "Asia/Shanghai"
    links:
      - jmalcloud
    restart: unless-stopped
```

**Comment by catbei2020** [comment]
好的，感谢！这个跳转在哪里改？默认好像是blog/
![image](https://github.com/user-attachments/assets/ab01f90c-a68a-4d8e-812b-93a6c8b1bb95)

**Comment by jamebal** [comment]
> 好的，感谢！这个跳转在哪里改？默认好像是blog/ ![image](https://private-user-images.githubusercontent.com/56509643/370096609-ab01f90c-a68a-4d8e-812b-93a6c8b1bb95.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxNDIxNTgsIm5iZiI6MTcyNzE0MTg1OCwicGF0aCI6Ii81NjUwOTY0My8zNzAwOTY2MDktYWIwMWY5MGMtYTY4YS00ZDhlLTgxMmItOTNhNmM4YjFiYjk1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI0VDAxMzczOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjNGU2MmMzZWY2MmUzOGMxYTExZTQzZTZlYTYzZjAzMjA4ZWQ0MWE0ZWM5ZmVkMTk1M2VlYTkzODA1YjdhMDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.HUIzcDw45L6gxgTf8sHZgIiAaxApQKj3sJI5bjMq4Xg)

系统管理-菜单管理

**Comment by jamebal** [comment]
> 嗯嗯，试了一下，移动端可以正常打开，但电脑端就一直卡状态，我only用的是自己的，8.1的版本，会不会是适配的问题呢？ 另外，因为已经有了only服务器，jmal不想再部署，yaml文件删除only的话，nginx容器就启不来，应该如何设置？

移动端和电脑端使用的office地址是一样的, 现在电脑端还是打不开吗

**Comment by catbei2020** [comment]
确定是我only镜像的问题，更换之后可以正常使用。谢谢！

**Comment by catbei2020** [comment]
> yaml文件删除office, nginx中的links也要删除office
> 
> ```yaml
> services:
>   mongo:
>     container_name: jmalcloud_mongodb
>     image: mongo:4.4
>     environment:
>       TZ: "Asia/Shanghai"
>     volumes:
>       - ./docker/jmalcloud/mongodb/data/db:/data/db
>       - ./docker/jmalcloud/mongodb/backup:/dump
>     restart: unless-stopped
>     healthcheck:
>       test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
>       interval: 10s
>       timeout: 5s
>       retries: 3
>     command: --wiredTigerCacheSizeGB 0.5
> 
>   jmalcloud:
>     container_name: jmalcloud_server
>     image: jmal/jmalcloud:latest
>     environment:
>       MONGODB_URI: "mongodb://mongo:27017/jmalcloud"
>       TZ: "Asia/Shanghai"
>       JVM_OPTS: "-Xms256m -Xmx512m"
>     volumes:
>       - ./docker/jmalcloud/files:/jmalcloud/files/
>     restart: unless-stopped
>     depends_on:
>       mongo:
>         condition: service_healthy
> 
>   nginx:
>     container_name: jmalcloud_nginx
>     image: jmal/jmalcloud-nginx:latest
>     ports:
>       - 7070:80
>       - 7071:8089
>     environment:
>       TZ: "Asia/Shanghai"
>     links:
>       - jmalcloud
>     restart: unless-stopped
> ```



> yaml文件删除office, nginx中的links也要删除office
> 
> ```yaml
> services:
>   mongo:
>     container_name: jmalcloud_mongodb
>     image: mongo:4.4
>     environment:
>       TZ: "Asia/Shanghai"
>     volumes:
>       - ./docker/jmalcloud/mongodb/data/db:/data/db
>       - ./docker/jmalcloud/mongodb/backup:/dump
>     restart: unless-stopped
>     healthcheck:
>       test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
>       interval: 10s
>       timeout: 5s
>       retries: 3
>     command: --wiredTigerCacheSizeGB 0.5
> 
>   jmalcloud:
>     container_name: jmalcloud_server
>     image: jmal/jmalcloud:latest
>     environment:
>       MONGODB_URI: "mongodb://mongo:27017/jmalcloud"
>       TZ: "Asia/Shanghai"
>       JVM_OPTS: "-Xms256m -Xmx512m"
>     volumes:
>       - ./docker/jmalcloud/files:/jmalcloud/files/
>     restart: unless-stopped
>     depends_on:
>       mongo:
>         condition: service_healthy
> 
>   nginx:
>     container_name: jmalcloud_nginx
>     image: jmal/jmalcloud-nginx:latest
>     ports:
>       - 7070:80
>       - 7071:8089
>     environment:
>       TZ: "Asia/Shanghai"
>     links:
>       - jmalcloud
>     restart: unless-stopped
> ```



> yaml文件删除office, nginx中的links也要删除office
> 
> ```yaml
> services:
>   mongo:
>     container_name: jmalcloud_mongodb
>     image: mongo:4.4
>     environment:
>       TZ: "Asia/Shanghai"
>     volumes:
>       - ./docker/jmalcloud/mongodb/data/db:/data/db
>       - ./docker/jmalcloud/mongodb/backup:/dump
>     restart: unless-stopped
>     healthcheck:
>       test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
>       interval: 10s
>       timeout: 5s
>       retries: 3
>     command: --wiredTigerCacheSizeGB 0.5
> 
>   jmalcloud:
>     container_name: jmalcloud_server
>     image: jmal/jmalcloud:latest
>     environment:
>       MONGODB_URI: "mongodb://mongo:27017/jmalcloud"
>       TZ: "Asia/Shanghai"
>       JVM_OPTS: "-Xms256m -Xmx512m"
>     volumes:
>       - ./docker/jmalcloud/files:/jmalcloud/files/
>     restart: unless-stopped
>     depends_on:
>       mongo:
>         condition: service_healthy
> 
>   nginx:
>     container_name: jmalcloud_nginx
>     image: jmal/jmalcloud-nginx:latest
>     ports:
>       - 7070:80
>       - 7071:8089
>     environment:
>       TZ: "Asia/Shanghai"
>     links:
>       - jmalcloud
>     restart: unless-stopped
> ```

yaml文件删除office, nginx中的links也要删除office后，貌似nginx容器就启不来了，如图：

![QQ截图20241025001828](https://github.com/user-attachments/assets/dc0fea86-ae28-4ced-80d7-80b221b0cfcf)

**Comment by jamebal** [comment]
### 删除office后, nginx容器起不来的临时解决办法

  使用`extra_hosts`将`office`指向某个可用的 IP 地址（例如 10.10.30.30）
```yaml
  nginx:
    container_name: jmalcloud_nginx
    image: jmal/jmalcloud-nginx:latest
    ports:
      - 7070:80
      - 7071:8089
    environment:
      TZ: Asia/Shanghai
    links:
      - jmalcloud
    restart: unless-stopped
    extra_hosts:
      - "office:10.10.30.30"
```
