### ISSUE TITLE
关于重建索引时卡在某个进度

### ISSUE THREAD

**Issue by HZJprince** [jamebal/jmal-cloud-view#321]
你好，上传文件以后，对某个文件夹进行重建索引时，会卡在某个进度，请问这个有什么好的解决？
![screenshot-1732713477818](https://github.com/user-attachments/assets/0b1ca1ab-a006-4544-af7a-369011dd1514)

**Comment by jamebal** [comment]
有bug，下个版本修复

**Comment by jamebal** [comment]
目前的解决办法:如果一直在卡住，可以重启jmalcloud_server容器。

实际上是扫描完了，进度显示有问题

**Comment by HZJprince** [comment]
主要是最近使用过程中，发现上传文件夹以后，有部分文件夹里面的文档使用关键字搜索，是搜索不出具有相应内容的文档（有docx格式，有pdf格式的），怀疑没有建索引，就用到重建索引，然后就很容易卡了，批量上传文件夹很容易出现索引建不成功的情况

**Comment by jamebal** [comment]
单独上传那个搜不到的文档, 看看能搜索到吗

**Comment by HZJprince** [comment]
单独上传是可以的

**Comment by jamebal** [comment]
> 单独上传是可以的

放在文件夹里上传就搜索不到是吧

**Comment by HZJprince** [comment]
嗯嗯，如果放在文件夹里，并且文件夹内文件量比较多时，就搜不到了

**Comment by jamebal** [comment]
> 嗯嗯，如果放在文件夹里，并且文件夹内文件量比较多时，就搜不到了

文件夹内大概有多少个文件

**Comment by HZJprince** [comment]
有的文件夹都是word文档的话，有100个以上，如果都是pdf的话，可能10个左右，也有混杂的，一个文件夹在20-50m大小不等

**Comment by jamebal** [comment]
上传文件夹后搜索不到, 然后再重建索引还是搜索不到吗

**Comment by HZJprince** [comment]
对，点重建索引就会卡在某个进度，就算重启server后也是一样的情况

**Comment by jamebal** [comment]
看看server的日志:
```bash
docker logs jmalcloud_server
```

**Comment by HZJprince** [comment]
[new.txt](https://github.com/user-attachments/files/17941880/new.txt)
这是日志

**Comment by jamebal** [comment]
> [new.txt](https://github.com/user-attachments/files/17941880/new.txt) 这是日志

这是重建索引后的日志吗

**Comment by HZJprince** [comment]
是的

**Comment by jamebal** [comment]
可是试试目前的测试版本吗?
jmalcloud和nginx的镜像换成test
```yaml
  jmalcloud:
    container_name: jmalcloud_server
    image: jmal/jmalcloud:test
```
```yml
  nginx:
    container_name: jmalcloud_nginx
    image: jmal/jmalcloud-nginx:test
```

**Comment by HZJprince** [comment]
这个镜像拉不下来，有阿里云镜像的吗请问

**Comment by jamebal** [comment]
试试这个:
```yml
  jmalcloud:
    container_name: jmalcloud_server
    image: proxy.1panel.live/jmal/jmalcloud:test
```

```yml
  nginx:
    container_name: jmalcloud_nginx
    image: proxy.1panel.live/jmal/jmalcloud-nginx:test
```

**Comment by HZJprince** [comment]
[_jmalcloud_server_logs.txt](https://github.com/user-attachments/files/17942147/_jmalcloud_server_logs.txt)
这是启用test镜像后，进系统重新构建索引的日志

**Comment by jamebal** [comment]
测试版,重建索引还会卡住吗

**Comment by HZJprince** [comment]
会啊，还是卡的

**Comment by jamebal** [comment]
server中加入参数`LOG_LEVEL: info`, 再看看卡住后的日志
```yml
  jmalcloud:
    container_name: jmalcloud_server
    image: proxy.1panel.live/jmal/jmalcloud:test
    environment:
      LOG_LEVEL: info
...
```

**Comment by HZJprince** [comment]
[_jmalcloud_server_logs_1.txt](https://github.com/user-attachments/files/17942331/_jmalcloud_server_logs_1.txt)
这是卡住后的日志

**Comment by jamebal** [comment]
server中加入参数`JVM_OPTS: -Xms512m -Xmx2048m`, 再试试
```yml
  jmalcloud:
    container_name: jmalcloud_server
    image: proxy.1panel.live/jmal/jmalcloud:test
    environment:
      LOG_LEVEL: info
      JVM_OPTS: -Xms512m -Xmx2048m
...
```
