### ISSUE TITLE
API地址无法正常启动

### ISSUE THREAD

**Issue by Xiaoph123** [jamebal/jmal-cloud-view#326]
如题，我如何手动启动jmal的API功能

**Comment by Xiaoph123** [comment]
端口是7072，但是开通后并没有被占用7072端口，API服务没有启动成功，不知是什么原因
![image](https://github.com/user-attachments/assets/dd62e224-fe53-49a2-829a-4cbb754bfaaa)
![image](https://github.com/user-attachments/assets/faa2b8fb-e4bc-442d-8806-d1266cf5e1d7)

**Comment by jamebal** [comment]
<img width="1387" alt="截屏2024-11-30 22 56 27" src="https://github.com/user-attachments/assets/4afd505e-8c04-4824-8241-163ef5452fa9">
jmalcloud_server在另一个容器里

**Comment by Xiaoph123** [comment]
> <img alt="截屏2024-11-30 22 56 27" width="1387" src="https://private-user-images.githubusercontent.com/49510841/391244517-4afd505e-8c04-4824-8241-163ef5452fa9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI5Nzg5NjEsIm5iZiI6MTczMjk3ODY2MSwicGF0aCI6Ii80OTUxMDg0MS8zOTEyNDQ1MTctNGFmZDUwNWUtOGMwNC00ODI0LTgyNDEtMTYzZWY1NDUyZmE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTMwVDE0NTc0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlMzJhNjg1ZDM1YjQwOGMzNzQ4OWE3MDdhMWRiYmJiOTNhYWY3NzllYTk1YTI4MTkxZTE4YjE2ODA5ZjgxODcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.SS4Kz1URP4CAvbbR4N6kKG6xJlvECHJvA4k0oQymqwc"> jmalcloud_server在另一个容器里
我该怎么操作？
![image](https://github.com/user-attachments/assets/4a8a1a9e-9b5e-4df1-9a85-a75d7c0af5f9)

**Comment by Xiaoph123** [comment]
好像有报错
![image](https://github.com/user-attachments/assets/19161acc-cf2a-4e02-bb3c-ce30ce43873b)

**Comment by jamebal** [comment]
看看你的docker-compose.yml文件是什么样的

**Comment by Xiaoph123** [comment]
这是我的yml文件
```yml
services:
  mongo:
    container_name: jmalcloud_mongodb
    image: registry.cn-beijing.aliyuncs.com/jmalcloud/mongo:4.4
    environment:
      TZ: "Asia/Shanghai"
    volumes:
      - /mnt/redcatdata/jmal-cloud-server/docker/jmalcloud/mongodb/data/db:/data/db
      - /mnt/redcatdata/jmal-cloud-server/docker/jmalcloud/mongodb/custom:/etc/mongo
      - /mnt/redcatdata/jmal-cloud-server/docker/jmalcloud/mongodb/backup:/dump
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 3
    command: --wiredTigerCacheSizeGB 0.5

  jmalcloud:
    container_name: jmalcloud_server
    image: registry.cn-beijing.aliyuncs.com/jmalcloud/jmalcloud:latest
    environment:
      MONGODB_URI: "mongodb://mongo:27017/jmalcloud"
      TZ: "Asia/Shanghai"
      JVM_OPTS: "-Xms512m -Xmx1024m"
    volumes:
      - /mnt/redcatdata/jmal-cloud-server/docker/jmalcloud/files:/jmalcloud/files/
    restart: unless-stopped
    depends_on:
      mongo:
        condition: service_healthy

  nginx:
    container_name: jmalcloud_nginx
    image: registry.cn-beijing.aliyuncs.com/jmalcloud/jmalcloud-nginx:latest
    ports:
      - 7070:80
      - 7071:8089
    environment:
      TZ: "Asia/Shanghai"
    links:
      - jmalcloud
      - office
    restart: unless-stopped

  office: # Optional
    container_name: jmalcloud_office
    image: registry.cn-beijing.aliyuncs.com/jmalcloud/onlyoffice_documentserver:8.0.1
    environment:
      TZ: "Asia/Shanghai"
      JWT_SECRET: "P25rrddd"
    restart: unless-stopped

```
