### ISSUE TITLE
配置域名反向代理后，访问 api 405 错误

### ISSUE THREAD

**Issue by ProAlexUSC** [jamebal/jmal-cloud-view#364]
我的 docker compose
```
services:
  mongo:
    container_name: jmalcloud_mongodb
    image: registry.cn-beijing.aliyuncs.com/jmalcloud/mongo:4.4
    environment:
      TZ: "Asia/Shanghai"
    volumes:
      - ./docker/jmalcloud/mongodb/data/db:/data/db
      - ./docker/jmalcloud/mongodb/backup:/dump
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 3
    command: --wiredTigerCacheSizeGB 0.5

  jmalcloud:
    container_name: jmalcloud_server
    image: registry.cn-beijing.aliyuncs.com/jmalcloud/jmalcloud:latest
    environment:
      MONGODB_URI: "mongodb://mongo:27017/jmalcloud"
      TZ: "Asia/Shanghai"
      JVM_OPTS: "-Xms256m -Xmx1024m"
    volumes:
      - ./docker/jmalcloud/files:/jmalcloud/files/
    restart: unless-stopped
    depends_on:
      mongo:
        condition: service_healthy

  nginx:
    container_name: jmalcloud_nginx
    image: registry.cn-beijing.aliyuncs.com/jmalcloud/jmalcloud-nginx:latest
    ports:
      - 7070:80
      - 7071:8089
    environment:
      TZ: "Asia/Shanghai"
    links:
      - jmalcloud
      - office
    restart: unless-stopped

  office: # Optional
    container_name: jmalcloud_office
    image: registry.cn-beijing.aliyuncs.com/jmalcloud/onlyoffice_documentserver:8.0.1
    environment:
      TZ: "Asia/Shanghai"
      JWT_SECRET: "my_secret"
    restart: unless-stopped
```
我的 nginx proxy manager 配置如下
<img width="555" alt="Image" src="https://github.com/user-attachments/assets/35301217-fae8-4ced-a1d3-4f93f6aecfcf" />
其余没有额外配置，相当于仅仅是配置了 SSL 端口转发，发现前端界面正常，但访问 api 接口有 405 报错

<img width="1658" alt="Image" src="https://github.com/user-attachments/assets/c65328b6-0579-4497-a08b-ebefe38dc1f8" />

请问应该如何解决？（使用 http 本地 ip 访问没有问题）
