### ISSUE TITLE
关于WebDAV的使用问题

### ISSUE THREAD

**Issue by v5star** [jamebal/jmal-cloud-view#86]
我测试的环境：docker+ jmal-cloud v2.7.1
在登录账号后，左下角有个WebDAV的图标以及链接，使用此链接使用WebDAV客户端挂载到本地后：
1、可以上传文件，复制文件，成功上传到服务器
2、不能获取列表（这个有点严重），就是你新建的或原有的，都拉不下来，本地复制上去，过一会刷新就没有了。（实际上服务器里是存在的）
3、不能重命名，不管是文件还是文件夹都不行。移动文件夹就测试不了。
4、容易卡死。
![7](https://github.com/jamebal/jmal-cloud-view/assets/31580191/0167fb5b-a7be-4dc0-9066-3129ff1a70c8)

我的猜测：
1、从webdav链接里访问出现的是Apache Tomcat/10.1.19，但是我们前端使用的是nginx/1.25.4，这里可能会出现原生的nginx对webdav的功能支持不全，如：PROPFIND OPTIONS LOCK UNLOCK，可能需要编译一些插件进去，比如：nginx-dav-ext-module。
2、还有一种可能就是，访问规则没有写好。

希望大佬们测试一下，然后更新一下这个功能，十分感谢。

**Comment by jamebal** [comment]
v2.8.1已修复该问题

**Comment by jamebal** [comment]
如果使用`https`访问, 所需的额外nginx配置:
```nginx
location / {
    proxy_pass http://localhost:7070; 
    proxy_set_header Host $http_host; 
    proxy_set_header X-Real-IP $remote_addr; 
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; 
    proxy_set_header X-Forwarded-Port $server_port;
    proxy_set_header REMOTE-HOST $remote_addr; 
    proxy_set_header Upgrade $http_upgrade; 
    proxy_set_header Connection "upgrade"; 
    proxy_set_header X-Forwarded-Proto $scheme; 
    proxy_http_version 1.1; 
    add_header X-Cache $upstream_cache_status; 
    add_header Strict-Transport-Security "max-age=31536000"; 
    add_header Cache-Control no-cache; 
}

location /webDAV/ {
    proxy_pass   http://localhost:7072/webDAV/;
    proxy_set_header Host $http_host;
    proxy_set_header Scheme $scheme;
    proxy_set_header X-Real-IP $remote_addr; 
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; 
    proxy_set_header REMOTE-HOST $remote_addr;
    proxy_set_header Upgrade $http_upgrade; 
    proxy_set_header Connection "upgrade"; 
    proxy_set_header X-Forwarded-Proto $scheme; 
    proxy_http_version 1.1; 
}
```

docker-compose.yml: 
```yml
version: "3"
services:
  jmalcloud:
    container_name: jmalcloud_server
    image: jmal/jmalcloud:latest
    environment:
      MONGODB_URI: mongodb://mongo:27017/jmalcloud
      TZ: Asia/Shanghai
    volumes:
      - ./docker/jmalcloud/files:/jmalcloud/files/
    ports:
      - 7072:8088
    restart: unless-stopped
  mongo:
    container_name: jmalcloud_mongodb
    image: mongo:4.4
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./docker/jmalcloud/mongodb/data/db:/data/db
    restart: unless-stopped
    command: --wiredTigerCacheSizeGB 0.5
  nginx:
    container_name: jmalcloud_nginx
    image: jmal/jmalcloud-nginx:latest
    ports:
      - 7070:80
      - 7071:8089
    environment:
      TZ: Asia/Shanghai
    links:
      - jmalcloud
      - office
      - drawio-webapp
    restart: unless-stopped
  office: # Optional
    container_name: jmalcloud_office
    image: onlyoffice/documentserver:7.0.0.132
    environment:
      TZ: Asia/Shanghai
    restart: unless-stopped
  drawio-webapp: # Optional
    container_name: jmalcloud_drawio
    image: jgraph/drawio:20.2.3
    environment:
      TZ: Asia/Shanghai
    restart: unless-stopped

```
