### ISSUE TITLE
webDAV 根据您提供的https方案似乎没有效果

### ISSUE THREAD

**Issue by Xiaoph123** [jamebal/jmal-cloud-view#90]
我使用的是win11,已关闭windows的防火墙

服务器使用centos7，docker部署方案

这是我的nginx配置：

```nginx
server {
    #网盘7000地址
    listen 9000 ssl;
    server_name xxxxxxx;  # 修改为你的域名或服务器 IP 地址
    # 证书配置
     ssl_certificate /www/server/nginx/xxxxxx_bundle.crt;
     ssl_certificate_key /www/server/nginx/xxxxxx.xkey;

    location / {
        #proxy_set_header Host $host; 
        proxy_pass http://localhost:7070;  # 网盘地址
        #webdav追加
        proxy_set_header Host $http_host; 
        proxy_set_header X-Real-IP $remote_addr; 
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Port $server_port;
        proxy_set_header REMOTE-HOST $remote_addr; 
        proxy_set_header Upgrade $http_upgrade; 
        proxy_set_header Connection "upgrade"; 
        proxy_set_header X-Forwarded-Proto $scheme; 
        proxy_http_version 1.1; 
        add_header X-Cache $upstream_cache_status; 
        add_header Strict-Transport-Security "max-age=31536000"; 
        add_header Cache-Control no-cache; 
        add_header 'Access-Control-Allow-Origin' '*'; 
    }
}


server {
    # #网盘7072地址
    listen 9001 ssl;
    server_name xxxxxx;  # 修改为你的域名或服务器 IP 地址
    # 证书配置
     ssl_certificate /www/server/nginx/xxxxxx_bundle.crt;
     ssl_certificate_key /www/server/nginx/xxxxxx.key;

    location / {
        proxy_pass http://localhost:7072/public/api;  #网盘API地址
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        add_header 'Access-Control-Allow-Origin' '*'; 
    }
    location /webDAV/ {
        proxy_pass   http://localhost:7072/webDAV/;
        proxy_set_header Host $http_host;
        proxy_set_header Scheme $scheme;
        proxy_set_header X-Real-IP $remote_addr; 
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header REMOTE-HOST $remote_addr;
        proxy_set_header Upgrade $http_upgrade; 
        proxy_set_header Connection "upgrade"; 
        proxy_set_header X-Forwarded-Proto $scheme; 
        proxy_http_version 1.1; 
        add_header 'Access-Control-Allow-Origin' '*';
}

}
```

并且我直接复制粘贴您给的docker-compose.yml配置

这是原来的docker-compose.yml配置：

```yaml
version: "3"
services:
  mongo:
    container_name: ${CONTAINER_NAME_PREFIX}_mongodb
    image: mongo:4.4
    environment:
      TZ: Asia/Shanghai
    ports:
      - 27018:27017
    volumes:
      - ${RESOURCE_DB_PATH}/data/db:/data/db
      - ${RESOURCE_DB_PATH}/custom:/etc/mongo
      - ${RESOURCE_DB_PATH}/backup:/dump
    restart: unless-stopped
    command: --wiredTigerCacheSizeGB 0.5
  jmalcloud:
    container_name: ${CONTAINER_NAME_PREFIX}_server
    image: jmal/jmalcloud:latest
    environment:
      MONGODB_URI: mongodb://mongo:27017/jmalcloud
      TZ: Asia/Shanghai
    ports:
      - ${SERVER_PORT}:8088
      - ${FTP_SERVER_PORT}:8089
    volumes:
      - ${RESOURCE_FILE_PATH}:/jmalcloud/files/
    restart: always
  nginx:
    container_name: ${CONTAINER_NAME_PREFIX}_nginx
    image: jmal/jmalcloud-nginx:latest
    ports:
      - ${APP_PORT}:80
      - ${BLOG_PORT}:8089
    environment:
      TZ: Asia/Shanghai
    links:
      - jmalcloud
      - office
      - drawio-webapp
    restart: always
  office:
    container_name: ${CONTAINER_NAME_PREFIX}_office
    image: onlyoffice/documentserver:${OFFICE_IMAGE_VERSION}
    environment:
      TZ: Asia/Shanghai
    restart: always
  drawio-webapp:
    container_name: ${CONTAINER_NAME_PREFIX}_drawio
    image: jgraph/drawio:${DRAWIO_IMAGE_VERSION}
    environment:
      TZ: Asia/Shanghai
    restart: always
networks: {}
```

现docker-compose.yml配置：

```yaml
version: "3"
services:
  jmalcloud:
    container_name: jmalcloud_server
    image: jmal/jmalcloud:latest
    environment:
      MONGODB_URI: mongodb://mongo:27017/jmalcloud
      TZ: Asia/Shanghai
    volumes:
      - ./docker/jmalcloud/files:/jmalcloud/files/
    ports:
      - 7072:8088
    restart: unless-stopped
  mongo:
    container_name: jmalcloud_mongodb
    image: mongo:4.4
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./docker/jmalcloud/mongodb/data/db:/data/db
    restart: unless-stopped
    command: --wiredTigerCacheSizeGB 0.5
  nginx:
    container_name: jmalcloud_nginx
    image: jmal/jmalcloud-nginx:latest
    ports:
      - 7070:80
      - 7071:8089
    environment:
      TZ: Asia/Shanghai
    links:
      - jmalcloud
      - office
      - drawio-webapp
    restart: unless-stopped
  office: # Optional
    container_name: jmalcloud_office
    image: onlyoffice/documentserver:7.0.0.132
    environment:
      TZ: Asia/Shanghai
    restart: unless-stopped
  drawio-webapp: # Optional
    container_name: jmalcloud_drawio
    image: jgraph/drawio:20.2.3
    environment:
      TZ: Asia/Shanghai
    restart: unless-stopped

```

更改yml文件并重启网盘，挂在到windows11上还是无法使用webDAV，

重命名提示报错信息：

![mmexport1715429176140.png](https://github.com/jamebal/jmal-cloud-view/assets/106538519/57b1e42d-0279-4edc-a7b3-f751a97c846d)

上传文件时：

![mmexport1715429178817.png](https://github.com/jamebal/jmal-cloud-view/assets/106538519/ea6ba127-183b-423e-938b-157900128c12)

上传文件夹时只能上传文件夹，不能上传文件夹内的文件

从网盘中复制粘贴文件夹时倒是可以粘贴过来，但是里面的文件无法正常打开

请您帮忙看下，我的配置是否有问题
